spring:
  application:
    name: lotto-check
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
app:
  lotto:
    client:
      host: https://developers.lotto.pl
      endpoints:
        byDatePerGame: /api/open/v1/lotteries/draw-results/by-date-per-game

