create table if not exists lotto_numbers (
    id bigint generated by default as identity primary key
);

create table if not exists lotto_card (
    id bigint generated by default as identity primary key,
    owner_subject varchar(255) not null,
    first_draw_date date,
    number_of_drawings integer not null,
    draw_type varchar(255)
);

create table if not exists lotto_card_numbers (
    lotto_card_id bigint not null,
    lotto_numbers_id bigint not null unique,
    constraint fk_lotto_card_numbers_card
        foreign key (lotto_card_id) references lotto_card (id),
    constraint fk_lotto_card_numbers_numbers
        foreign key (lotto_numbers_id) references lotto_numbers (id)
);

create table if not exists lotto_numbers_values (
    lotto_numbers_id bigint not null,
    number_value integer not null,
    constraint fk_lotto_numbers_values_numbers
        foreign key (lotto_numbers_id) references lotto_numbers (id)
);

create index if not exists idx_lotto_card_owner_id on lotto_card (owner_subject, id desc);
